In [2]:
import numpy as np
import csv
from scipy.stats import f_oneway

In [3]:
methods = ['Differential Evolution','Cheung 2004','Finlayson 2015','Vandermonde']
datos = {"arrachera":[], "sirloin":[], "bola":[]}
with open('errores_calibracion_colores.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        datos[row[0]].append(np.array([float(item) for item in row[2:]]))

datos["bola"]

[array([0. , 2. , 2. , ..., 3. , 2. , 3.5]),
 array([1., 0., 1., ..., 4., 2., 1.]),
 array([1., 0., 1., ..., 4., 2., 1.]),
 array([8. , 7. , 6. , ..., 4. , 1.5, 0. ])]

In [4]:
for key,value in datos.items():
    print(key)
    result = f_oneway(*datos[key])
    print(result)

arrachera
F_onewayResult(statistic=103.4536252868159, pvalue=9.331329371972143e-66)
sirloin
F_onewayResult(statistic=62.89027569943982, pvalue=3.342112901882239e-40)
bola
F_onewayResult(statistic=97.7914948965733, pvalue=3.2964922029789467e-62)
